services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /src
    ports:
      - "5173:5173"
